---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: litmus-percona- 
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: percona-deployment
   
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner
        imagePullPolicy: Always

        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

          - name: PROVIDER_STORAGE_CLASS
            # Supported values: openebs-standard, local-storage
            value: openebs-standard

          - name: APP_PVC
            value: percona-mysql-claim

            # Application label
          - name: APP_LABEL
            value: 'name=percona'

            # Application namespace
          - name: APP_NAMESPACE
            value: litmus
 
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./percona/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"]
        
