apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  annotations:
    probeRef: '[{"name":"http-probe"}]'
  generateName: nginx-chaos
  name: nginx-chaos
  namespace: default
spec:
  appinfo:
    appns: 'default'
    applabel: 'app=nginx'
    appkind: 'deployment'
  # It can be active/stop
  engineState: 'active'
  chaosServiceAccount: pod-delete-sa
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '30'

            # set chaos interval (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '10'

            # pod failures without '--force' & default terminationGracePeriodSeconds
            - name: FORCE
              value: 'false'

            ## percentage of total pods to target
            - name: PODS_AFFECTED_PERC
              value: ''