---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: storageclass-setup-
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
      labels:
        provider: openebs-sc-setup
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always
        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            value: default
          - name: RUN_ID
            value:
          # Enable storageclass
          - name: APPLY_JIVA
            value: "false"
          - name: APPLY_CSTOR
            value: "false"
          # Jiva configuration
          - name: JIVA_POOL_NAME
            value: openebs-mntdir
          - name: JIVA_STORAGECLASS_NAME
            value: openebs-storageclass
          - name: STORAGE_PATH
            value: /mnt/openebs
          - name: OPENEBS_IO_JIVA_REPLICA_COUNT
            value: "3"
          - name: OPENEBS_IO_JIVA_CONTROLLER_IMAGE
            value: openebs/jiva:0.7.0
          - name: OPENEBS_IO_JIVA_REPLICA_IMAGE
            value: openebs/jiva:0.7.0
          - name: OPENEBS_IO_VOLUME_MONITOR_IMAGE
            value: openebs/m-exporter:ci
          # Cstor configuration
          - name: CSTOR_POOL_NAME
            value: cstor-pool-default-0.7.0
          - name: MAX_POOLS
            value: "3"
          - name: CSTOR_CONTROLLER_IMAGE
            value: openebs-cstor-default-0.7.0
          - name: CSTOR_STORAGECLASS_NAME
            value: openebs-cstor-default-0.7.0
          - name: DISK_LIST
            value: 
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./providers/openebs/installers/storageclass/0.7/ansible/storageclass_setup.yaml -i /etc/ansible/hosts -vv; exit 0"]
