version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "chaoscenter/authentication"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "chaoscenter/event-tracker"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "chaoscenter/subscriber"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/argoproj/argo-workflows/v3"

  - package-ecosystem: "gomod"
    directory: "chaoscenter/graphql/server"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/argoproj/argo-workflows/v3"