---
exclude_paths:
  - "chaoscenter/web/src/api/auth/**"
  - "chaoscenter/web/src/components/YAMLBuilder/YamlBuilder.module.scss.d.ts"
  - "chaoscenter/web/src/components/ThemeToggle/ThemeToggle.module.scss.d.ts"
  - "chaoscenter/web/src/components/ThemeToggle/ThemeSegmentedControl.module.scss.d.ts"
