---
apiVersion: v1
kind: Namespace
metadata:
  name: litmus
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: litmus-portal-operations-config
  namespace: litmus
data:
  K8s-mode: cluster
  SubscriberNamespace: litmus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusportal-frontend
  namespace: litmus
  labels:
    component: litmusportal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: litmusportal-frontend
  template:
    metadata:
      labels:
        component: litmusportal-frontend
    spec:
      containers:
        - name: litmusportal-frontend
          image: litmuschaos/litmusportal-frontend:ci
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: litmusportal-frontend-service
  namespace: litmus
spec:
  type: NodePort
  ports:
    - name: http
      port: 9091
      targetPort: 80
  selector:
    component: litmusportal-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: self-deployer-admin-account
  namespace: litmus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: deployer-admin
  namespace: litmus
  labels:
    name: deployer-admin
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - customresourcedefinitions
      - serviceaccounts
      - roles
      - clusterroles
      - rolebindings
      - clusterrolebindings
      - configmaps
      - deployments
      - pods
    verbs:
      - "create"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: deployer-admin-rb
  namespace: litmus
subjects:
  - kind: ServiceAccount
    name: self-deployer-admin-account
    namespace: litmus
roleRef:
  kind: ClusterRole
  name: deployer-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusportal-server
  namespace: litmus
  labels:
    component: litmusportal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: litmusportal-server
  template:
    metadata:
      labels:
        component: litmusportal-server
    spec:
      containers:
        - name: graphql-server
          image: litmuschaos/litmusportal-server:ci
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
          env:
            - name: DB_SERVER
              value: "mongo-service:27017"
            - name: JWT_SECRET
              value: "litmus-portal@123"
            - name: EXTERNAL_ADDRESS
              value: ""
            - name: SERVICE_ADDRESS
              value: "http://litmusportal-server-service:9002"
            - name: SELF_CLUSTER
              value: "true"
            - name: SUBSCRIBER_IMAGE
              value: "litmuschaos/litmusportal-subscriber:ci"
            - name: SUBSCRIBER_SCOPE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-operations-config
                  key: K8s-mode
            - name: AGENT_SCOPE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-operations-config
                  key: K8s-mode
            - name: SUBSCRIBER_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-operations-config
                  key: SubscriberNamespace
            - name: AGENT_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-operations-config
                  key: SubscriberNamespace
            - name: DEPLOYER_IMAGE
              value: "litmuschaos/litmusportal-self-deployer:ci"
            - name: DEPLOYER_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-operations-config
                  key: SubscriberNamespace
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
        - name: auth-server
          image: litmuschaos/litmusportal-auth-server:ci
          resources:
            limits:
              cpu: 200m
              memory: 250Mi
          env:
            - name: DB_SERVER
              value: "mongodb://mongo-service:27017"
            - name: JWT_SECRET
              value: "litmus-portal@123"
            - name: ADMIN_USERNAME
              value: "admin"
            - name: ADMIN_PASSWORD
              value: "litmus"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      serviceAccountName: litmus-svc-account
---
apiVersion: v1
kind: Service
metadata:
  name: litmusportal-server-service
  namespace: litmus
spec:
  type: ClusterIP
  ports:
    - name: graphql-server
      port: 9002
      targetPort: 8080
    - name: auth-server
      port: 9003
      targetPort: 3000
  selector:
    component: litmusportal-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: litmus
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
    spec:
      containers:
        - name: mongo
          image: mongo:4.2.8
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 27017
          imagePullPolicy: Always
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: litmus
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-service
  namespace: litmus
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    component: database
