---
- hosts: localhost
  gather_facts: yes

  vars_files:
    - vars.yml
  vars:
    cluster_name:
    set_zone:
    test_case_name: "GKE_DELETE_CLUSTER"

  tasks:
    - block:
        - name: Fetch Cluster Name
          shell: cat ~/logs/clusters
          register: cluster_name
          when: not cluster_name

        - name: Fetch Zone
          shell: cat ~/logs/zone
          register: set_zone
          when: not set_zone

        - set_fact:
            cluster_name: "{{ cluster_name.stdout }}"
          when: cluster_name.stdout is defined

        - set_fact:
            set_zone: "{{ set_zone.stdout }}"
          when: set_zone.stdout is defined

        - name: Delete GKE cluster
          gcp_container_cluster:
            name: "{{ cluster_name }}"
            initial_node_count: "{{ initial_node_count }}"
            monitoring_service: none 
            node_config:
              machine_type: "{{ machine_type }}"
              disk_size_gb: "{{ disk_size_gb }}"
              image_type: "{{ image_type }}"
              oauth_scopes:
                - https://www.googleapis.com/auth/cloud-platform
            zone: "{{ set_zone }}"
            project: "{{ project }}"
            auth_kind: "{{ auth_kind }}"
            scopes:
              - https://www.googleapis.com/auth/cloud-platform
            state: absent

        - name: Remove Cluster Info
          lineinfile:
            state: absent
            path: "~/logs/clusters"
            regexp: "{{ cluster_name }}"

        - name: Remove Zone Info
          lineinfile:
            state: absent
            path: "~/logs/zone"
            regexp: "{{ set_zone }}"

        - name: Set Test Status
          set_fact:
            flag: "Test Passed"

      rescue:  
        - name: Set Test Status
          set_fact:
            flag: "Test Failed"
