{
 "title": "Node and Pod Chaos Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Litmus Chaos Chaos durations interleaved with Node Exporter & Kube-State Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Chaos - Node - CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate1m",
     "legendFormat": "\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Chaos - Node - Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio",
     "legendFormat": "\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Chaos - Pod - CPU Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",pod!=\"\"}[5m])) by (pod)",
     "legendFormat": "\"{{pod}}\""
    }
   ]
  },
  {
   "title": "Chaos - Pod - Memory Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",container!=\"\"}) by (pod)",
     "legendFormat": "\"{{pod}}\""
    }
   ]
  }
 ]
}