---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgset-sa
---
apiVersion: v1
kind: Service
metadata:
  name: pgset
  labels:
    lkey: lvalue
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    name: web
  clusterIP: None
  selector:
    app: pgset
---  
kind: Service
apiVersion: v1
metadata:
  name: pgset-primary
  labels:
    name: pgset-primary
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 0
  selector:
    name: pgset-primary
  type: ClusterIP
  sessionAffinity: None
---
kind: Service
apiVersion: v1
metadata:
  name: pgset-replica
  labels:
    name: pgset-replica
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 0
  selector:
    name: pgset-replica
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: pgset
spec:
  serviceName: pgset
  replicas: 2
  template:
    metadata:
      labels:
        lkey: lvalue
        affinity_label: pgset
    spec:
      securityContext:
        fsGroup: 26
      containers:
      - name: pgset
        image: crunchydata/crunchy-postgres:centos7-10.0-1.6.0
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: PG_PRIMARY_USER
          value: primaryuser
        - name: PGHOST
          value: "/tmp"
        - name: PG_MODE
          value: set
        - name: PG_PRIMARY_PASSWORD
          value: password
        - name: PG_USER
          value: testuser
        - name: PG_PASSWORD
          value: password
        - name: PG_DATABASE
          value: userdb
        - name: PG_ROOT_PASSWORD
          value: password
        - name: PG_PRIMARY_PORT
          value: '5432'
        - name: PG_PRIMARY_HOST
          value: pgset-primary
        volumeMounts:
        - name: testclaim
          mountPath: "/pgdata"
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: testclaim
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: testclass
      resources:
        requests:
          storage: volume-capacity
