---
apiVersion: batch/v1
kind: Job
metadata:
  name: litmus-pgset
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
      labels:
        app: postgres-deploy-litmus
   
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: mockbot/postsathya:v01
        imagePullPolicy: Always

        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays, actionable, default
            value: default

          - name: PROVIDER_STORAGE_CLASS
            # Supported values: openebs-standard, local-storage
            value: openebs-standard

          - name: PROVIDER_PVC
            value: pgdata-claim

          - name: DEPLOY_TYPE
            value: statefulset
 
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./crunchy-postgres/deployers/test.yml -i /etc/ansible/hosts -v; exit 0"] 
