/**
* This file is auto-generated. Please do not modify this file manually.
* Use the command `yarn strings` to regenerate this file.
*/
export type PrimitiveObject<T extends string> = Record<T, string | number | boolean>

export interface StringsMap {
    '404Error': unknown
  'FRI': unknown
  'MON': unknown
  'NASlash': unknown
  'SAT': unknown
  'SUN': unknown
  'THU': unknown
  'TUE': unknown
  'WED': unknown
  'aboutChaosCTL': unknown
  'accessToAllNamespaces': unknown
  'accessType': unknown
  'account': unknown
  'accountSettings': unknown
  'accountURL': unknown
  'actionItems': unknown
  'active': unknown
  'actualResilienceScore': unknown
  'add': unknown
  'addExperimentToChaosHub': unknown
  'addNewCluster': unknown
  'addNodeSelectorAgentDeployment': unknown
  'addProbe': unknown
  'addResilienceStep': unknown
  'addRow': unknown
  'addToChaosHub': unknown
  'addToTemplate': unknown
  'addTolerationAgentDeployment': unknown
  'addViewSummaryNotes': unknown
  'addtoHubLoading': unknown
  'advanced': unknown
  'advancedOptions': unknown
  'all': unknown
  'allChaosEnabled': unknown
  'allFaultsExecuted': unknown
  'allRuns': unknown
  'alreadyExists': PrimitiveObject<'value'>
  'appKind': unknown
  'appKindName': unknown
  'appLabel': unknown
  'appLabelName': unknown
  'appNameSpace': unknown
  'apply': unknown
  'applyChanges': unknown
  'at': unknown
  'atAGlance': unknown
  'authenticationType': unknown
  'averageResilienceScore': unknown
  'back': unknown
  'basic': unknown
  'blankCanvasDescription': unknown
  'blankCanvasTitle': unknown
  'blobLogsNotAvailable': unknown
  'cancel': unknown
  'cannotPushToDefault': unknown
  'cannotReRun': unknown
  'chaos': unknown
  'chaosComponentInstallation': unknown
  'chaosController': unknown
  'chaosEnableFailed': unknown
  'chaosEngineName': unknown
  'chaosEngineResult': unknown
  'chaosExperiment': unknown
  'chaosExperiments': unknown
  'chaosFaults': unknown
  'chaosHub': unknown
  'chaosHubExperiment': unknown
  'chaosHubFault': unknown
  'chaosHubNoExp': unknown
  'chaosHubNoFault': unknown
  'chaosHubNoSearchExperiment': PrimitiveObject<'searchTerm'>
  'chaosHubNoSearchFault': PrimitiveObject<'searchTerm'>
  'chaosHubReferenceFielPlaceholder': unknown
  'chaosHubStep1': unknown
  'chaosHubStep2': unknown
  'chaosHubStep3': unknown
  'chaosIncidentsDetected': unknown
  'chaosIncidentsDiscovered': unknown
  'chaosInfraVersionAvailable': PrimitiveObject<'version'>
  'chaosInfrastructureDesc': unknown
  'chaosInfrastructureDescription': unknown
  'chaosInfrastructureDetails': unknown
  'chaosInfrastructureLogs': unknown
  'chaosInfrastructureNamespace': unknown
  'chaosInfrastructureOverview': unknown
  'chaosInfrastructureSuccess': unknown
  'chaosInfrastructureText': unknown
  'chaosInfrastructures': unknown
  'chaosResultNotAvailable': unknown
  'chaosResults': unknown
  'chaosStudio': unknown
  'chaoshubDisconnectedWillSync': unknown
  'chaoshubs': unknown
  'checkConnection': unknown
  'checkLogs': unknown
  'checkStatus': unknown
  'chooseAccessType': unknown
  'chooseAuthenticationType': unknown
  'chooseHubAccess': unknown
  'clickDownload': unknown
  'clone': unknown
  'cloneExperiment': unknown
  'closeTuneConfirmation': unknown
  'closeTuneConfirmationDescription': unknown
  'clusterScopeDescription': unknown
  'clusterWide': unknown
  'clusterWideAccess': unknown
  'cmdDescription': unknown
  'cmdProbeDetails': unknown
  'cmdProbeTitle': unknown
  'collaborators': unknown
  'comingSoon': unknown
  'command': unknown
  'comparator': unknown
  'completed': unknown
  'configure': unknown
  'configureChaosInfrastructure': unknown
  'configureDetails': unknown
  'configureProperties': unknown
  'confirm': unknown
  'confirmText': unknown
  'connectChaosHub': unknown
  'connectHub': unknown
  'connectInfraKubernetes': unknown
  'connectInfraTooltip': unknown
  'connected': unknown
  'connectingChaosHub': unknown
  'connectionModal.method': unknown
  'connectionModal.options.option1.icon': unknown
  'connectionModal.options.option1.text': unknown
  'connectionModal.options.option2.icon': unknown
  'connectionModal.options.option2.text': unknown
  'connectionStatus': unknown
  'consoleLogs': unknown
  'continue': unknown
  'copyPrompt': unknown
  'copyPrompt1': unknown
  'copyPrompt2': unknown
  'crdCopyPrompt': unknown
  'createChaosExperiment': unknown
  'createNamespace': unknown
  'createRecurringSchedule': unknown
  'created': unknown
  'createdOn': unknown
  'creationTime': unknown
  'criteria': unknown
  'cronExpression': unknown
  'cronExpressionRequired': unknown
  'cronSelectOption': unknown
  'cronText': unknown
  'currentRun': unknown
  'currentUTCTime': unknown
  'customLabel': unknown
  'daily': unknown
  'dailyMessage': unknown
  'dateExecuted': unknown
  'dayOfMonthLabel': unknown
  'dayOfWeekLabel': unknown
  'degelateNotActive': unknown
  'delete': unknown
  'deleteChaosInfrastructure': unknown
  'deleteExperiment': unknown
  'deleteExperimentDesc': unknown
  'deleteExperimentHeading': unknown
  'deleteProbe': unknown
  'deleteProbeDesc': unknown
  'deleteProbeHeading': unknown
  'deleteSuccess': unknown
  'deployChaosInfrastructure': unknown
  'deployProbe': unknown
  'deploySetup': unknown
  'deployedOn': unknown
  'description': unknown
  'descriptionOptional': unknown
  'details': unknown
  'detailsAndProperties': unknown
  'disable': unknown
  'disableChaosInfrastructure': unknown
  'discard': unknown
  'discardExperiment': unknown
  'disconnectDescriptionClusterMode': unknown
  'disconnectDescriptionNamespaceMode': unknown
  'disconnected': unknown
  'done': unknown
  'download': unknown
  'downloadChaosInfrastructureManifest': unknown
  'downloadExperiment': unknown
  'downloadSuccess': unknown
  'downloadYAML': unknown
  'downloadYAMLFile': unknown
  'downloadedSuccessfully': unknown
  'duration': unknown
  'edit': unknown
  'editChaosHub': unknown
  'editExperiment': unknown
  'editExperimentCopy': unknown
  'editExperimentOptions': unknown
  'editExperimentSame': unknown
  'editHubDescription': unknown
  'editInChaosStudio': unknown
  'editProbe': unknown
  'editSameExperimentDescription': unknown
  'editSameExperimentTitle': unknown
  'editYaml': unknown
  'editingChaosHub': unknown
  'effect': unknown
  'enableChaosInfraButton': unknown
  'enableChaosInfrastructure': unknown
  'enableChaosInfrastructureDesc': unknown
  'enableImageRegistryChanges': unknown
  'enableSSLCheck': unknown
  'enablingChaos': unknown
  'endTime': unknown
  'endedAt': unknown
  'endpoint': unknown
  'enterCustomCron': unknown
  'enterHubAccountURL': unknown
  'enterHubName': unknown
  'enterHubRepositoryBranch': unknown
  'enterHubRepositoryName': unknown
  'enterHubRepositoryURL': unknown
  'environment': unknown
  'environmentError': unknown
  'environments': unknown
  'error': unknown
  'errorApplyChanges': unknown
  'errorFetchName': unknown
  'executedBy': unknown
  'executedOn': unknown
  'executionDetails': unknown
  'executionError': unknown
  'executionHistory': unknown
  'executionOverview': unknown
  'executionStatus': unknown
  'exhausted': unknown
  'expCategory': unknown
  'expDesc': unknown
  'expName': unknown
  'expSaved': unknown
  'expectedResilienceScore': unknown
  'expectedResponseCode': unknown
  'experiment': unknown
  'experimentActivity': unknown
  'experimentBuilder': unknown
  'experimentDeleted': unknown
  'experimentDeletedSuccessfully': unknown
  'experimentID': unknown
  'experimentInFault': unknown
  'experimentIsRunning': unknown
  'experimentNamespace': unknown
  'experimentOverview': unknown
  'experimentPreview': unknown
  'experimentRunDetails': unknown
  'experimentRunID': unknown
  'experimentRuns': unknown
  'experimentStopSuccessMessage': unknown
  'experimentType': unknown
  'experiments': unknown
  'expressionBreakdown': unknown
  'failStep': unknown
  'failed': unknown
  'failedRuns': unknown
  'fault': unknown
  'faultActivity': unknown
  'faultConfiguration': unknown
  'faultDetails': unknown
  'faultShouldHaveAtleastOneProbe': unknown
  'faultSummary': unknown
  'faultVerdict': unknown
  'faults': unknown
  'faultsContained': unknown
  'faultsHaveProbeFailures': unknown
  'faultsLibrary': unknown
  'featureRestriction.experimentsPerMonthLevelUp': PrimitiveObject<'count' | 'experimentsLimit'>
  'featureRestriction.initialDeploymentsWarningActive': PrimitiveObject<'warningLimit'>
  'featureRestriction.resourceLevelUpFree': PrimitiveObject<'resourceLimit' | 'resourceName'>
  'featureRestriction.resourceLevelUpTeam': PrimitiveObject<'resourceLimit'>
  'featureRestriction.resourceOveruseEnterprise': unknown
  'fieldSelector': unknown
  'genericResourceNotFoundError': PrimitiveObject<'resource' | 'resourceID' | 'projectID'>
  'gitConnection': unknown
  'goBack': unknown
  'goChaosHome': unknown
  'greatJob': unknown
  'group': unknown
  'healthy': unknown
  'history': unknown
  'hostedOn': unknown
  'hostedOnAgent': unknown
  'hourly': unknown
  'hourlyMessage': unknown
  'hoursAnd': unknown
  'hoursLabel': unknown
  'hoverFaultToViewDetails': unknown
  'howToFindServiceAccount': unknown
  'howToUseExp': unknown
  'httpDescription': unknown
  'httpProbeDetails': unknown
  'httpProbeTitle': unknown
  'hubAccess': unknown
  'hubConnectedSuccessfully': unknown
  'hubDeletedSuccessfully': unknown
  'hubEditedSuccessfully': unknown
  'hubName': unknown
  'hubRepositoryBranch': unknown
  'hubRepositoryURL': unknown
  'id': unknown
  'idlowerCase': unknown
  'improveResilienceOfTheDeployedService': unknown
  'inactive': unknown
  'inactiveTooltip': unknown
  'infraName': unknown
  'infrastructure': unknown
  'infrastructureCommand': unknown
  'infrastructureRegistered': unknown
  'infrastructureStates': unknown
  'infrastructureType': unknown
  'initialDelaySeconds': unknown
  'insecureSkipVerify': unknown
  'installYaml': unknown
  'interval': unknown
  'intervalOptional': unknown
  'invalidSelection': unknown
  'invalidText': unknown
  'isRequired': PrimitiveObject<'field'>
  'issueSupport': unknown
  'k8sDescription': unknown
  'k8sProbeDetails': unknown
  'k8sProbeTitle': unknown
  'key': unknown
  'kubectl': unknown
  'kubernetes': unknown
  'kubernetesChaosInfrastructureClusterScopeDeleteStepTwo': unknown
  'kubernetesChaosInfrastructureDeleteStepOne': unknown
  'kubernetesChaosInfrastructureNamespaceScopeDeleteStepFour': unknown
  'kubernetesChaosInfrastructureNamespaceScopeDeleteStepThree': unknown
  'kubernetesChaosInfrastructureNamespaceScopeDeleteStepTwo': unknown
  'kubernetesClusterDetails': unknown
  'kubernetesInfrastructureDeleteCRDSNote': unknown
  'kubernetesInfrastructureDeleteNote': unknown
  'kubernetesPermissions.nameSpace': unknown
  'kubernetesPermissions.statefulSets': unknown
  'kubernetesPrerequisites': unknown
  'kubernetesSetupInstructions': unknown
  'labelSelector': unknown
  'lastHeartBeat': unknown
  'lastModified': unknown
  'lastResilienceScore': unknown
  'lastRun': unknown
  'lastSyncedAt': unknown
  'latestRun': unknown
  'latestRunFallbackText': unknown
  'launchExperiment': unknown
  'learnMore': unknown
  'letsGetStarted': unknown
  'litmus': unknown
  'litmusChaos': unknown
  'loading': unknown
  'logErrorMessage': unknown
  'loginDescription': unknown
  'logs': unknown
  'logsOptional': unknown
  'mainTitle': unknown
  'manifestDownloadUnsuccessful': unknown
  'manifestMissing': unknown
  'manual': unknown
  'manualInterruption': unknown
  'markRunAsComplete': unknown
  'markRunAsCompleteDescription': unknown
  'meetsExpectations': unknown
  'menuItems.deleteHub': unknown
  'menuItems.editHub': unknown
  'menuItems.syncHub': unknown
  'menuItems.viewHub': unknown
  'method': unknown
  'minute': unknown
  'minutesAfterTheHour': unknown
  'minutesLabel': unknown
  'minutesParentheses': unknown
  'mode': unknown
  'moduleName': unknown
  'monitorCluster': unknown
  'monitorNamespace': unknown
  'monthLabel': unknown
  'monthly': unknown
  'monthlyMessage': unknown
  'monthsParentheses': unknown
  'mostRecentDirection': unknown
  'mustBeInteger': PrimitiveObject<'field'>
  'mustBePositive': PrimitiveObject<'field'>
  'myProfile': unknown
  'na': unknown
  'name': unknown
  'nameIdDescriptionTags.descriptionPlaceholder': unknown
  'nameIdDescriptionTags.namePlaceholder': unknown
  'nameIdDescriptionTags.optionalField': PrimitiveObject<'name'>
  'nameIdDescriptionTags.tagsLabel': unknown
  'namespace': unknown
  'namespaceScopeDescription': unknown
  'namespaceWide': unknown
  'needAttention': unknown
  'newChaosExperiment': unknown
  'newChaosHub': unknown
  'newChaosInfrastructure': unknown
  'newExperiment': unknown
  'newProbe': unknown
  'newUpdates': unknown
  'newUserNoExperiments.subtitle': unknown
  'newUserNoExperiments.title': unknown
  'newUserNoInfra.title': unknown
  'next': unknown
  'nextRun': unknown
  'nextSelectChaosExperiments': unknown
  'noAnalysis': unknown
  'noChaosHubSelected': unknown
  'noChaosInfrastructure': unknown
  'noChaosInfrastructureFound': unknown
  'noClustersFound': unknown
  'noData.message': unknown
  'noData.title': unknown
  'noDataCV': unknown
  'noDataToDisplay': unknown
  'noExpFound': unknown
  'noExperimentFoundMatchingSearch': unknown
  'noExperimentSelected': unknown
  'noExperiments': unknown
  'noExperimentsAdded': unknown
  'noFaults': unknown
  'noFilteredActiveInfra': unknown
  'noFilteredData.subtitle': unknown
  'noFilteredData.title': unknown
  'noHealthyState': unknown
  'noKubernetesChaosInfrastructureFound': PrimitiveObject<'value'>
  'noLogs': unknown
  'noMonitoredService': unknown
  'noProbeDescription': unknown
  'noProbes': unknown
  'noProbesAvailable': unknown
  'noProbesFound.errorMessage': unknown
  'noProbesFound.message': unknown
  'noProbesFound.title': unknown
  'noProjectFoundMatchingSearch': PrimitiveObject<'searchTerm'>
  'noResultsFound': unknown
  'noRunsFound': unknown
  'noRunsFoundForThisExperiment': unknown
  'noTunables': unknown
  'noWorkflowRun': unknown
  'nodeSelector': unknown
  'nodeSelectorPlaceholderForKey': unknown
  'nodeSelectorPlaceholderForValue': unknown
  'nodeSelectorText': unknown
  'nonCronSelectOption': unknown
  'nonCronText': unknown
  'nonProd': unknown
  'notMeetsExpectations': unknown
  'notMeetsExpectationsInterventionNeeded': unknown
  'notes': unknown
  'numberOfExperiments': unknown
  'objective': unknown
  'objectives': unknown
  'observe': unknown
  'ofEvery': unknown
  'on': unknown
  'onThe': unknown
  'onThisPage': unknown
  'openInNewTab': unknown
  'operation': unknown
  'operator': unknown
  'optional': unknown
  'or': unknown
  'orderBy': unknown
  'organization': unknown
  'outOf': unknown
  'outOfSmall': unknown
  'overallNodeResult': unknown
  'overallResiliencyScore': unknown
  'overview': unknown
  'overwriteYaml': unknown
  'parallel': unknown
  'passed': unknown
  'passedRuns': unknown
  'pauseRun': unknown
  'pending': unknown
  'pendingTime': unknown
  'phase': unknown
  'platform': unknown
  'pleaseComplete': unknown
  'pleaseSelectLeastOneExperiment': unknown
  'points': unknown
  'pollingInterval': unknown
  'preProd': unknown
  'predefinedExperimentsNotFound': unknown
  'preview': unknown
  'private': unknown
  'probeConfiguration': unknown
  'probeDetails': unknown
  'probeMode': unknown
  'probeModes.Continuous': unknown
  'probeModes.EOT': unknown
  'probeModes.Edge': unknown
  'probeModes.OnChaos': unknown
  'probeModes.SOT': unknown
  'probeName': unknown
  'probeOverview': unknown
  'probePassedSuccessfully': unknown
  'probeProperties': unknown
  'probeResult': unknown
  'probeResultNotAvailable': unknown
  'probeResultsInPastRuns': unknown
  'probeStatus': unknown
  'probeSuccessPercentage': unknown
  'probeSummary': unknown
  'probeType': unknown
  'probeTypes.cmdProbe': unknown
  'probeTypes.httpProbe': unknown
  'probeTypes.k8sProbe': unknown
  'probeTypes.promProbe': unknown
  'probeValidation.body': unknown
  'probeValidation.command': unknown
  'probeValidation.contentType': unknown
  'probeValidation.criteria': unknown
  'probeValidation.endpoint': unknown
  'probeValidation.getCriteria': unknown
  'probeValidation.getResponseCode': unknown
  'probeValidation.interval': unknown
  'probeValidation.method': unknown
  'probeValidation.name': unknown
  'probeValidation.namespace': unknown
  'probeValidation.pollingInterval': unknown
  'probeValidation.postCriteria': unknown
  'probeValidation.postResponseCode': unknown
  'probeValidation.query': unknown
  'probeValidation.responseTimeout': unknown
  'probeValidation.retry': unknown
  'probeValidation.timeout': unknown
  'probeValidation.type': unknown
  'probeValidation.url': unknown
  'probeValidation.value': unknown
  'probes': unknown
  'probesArePassed': unknown
  'prod': unknown
  'project': unknown
  'promDescription': unknown
  'promProbeDetails': unknown
  'promProbeTitle': unknown
  'properties': unknown
  'provideTargetApplicationDetails': unknown
  'public': unknown
  'query': unknown
  'queryPath': unknown
  'ranAt': unknown
  'rbacDescription': PrimitiveObject<'permission'>
  'rbacHeader': unknown
  'reRunDesc': unknown
  'reRunExperiment': unknown
  'reRunSuccessful': unknown
  'readMore': unknown
  'recentExecutionResults': unknown
  'recentExecutions': unknown
  'recentExperimentRuns': unknown
  'recentlyUsed': unknown
  'recurringRun': unknown
  'recurringSchedule': unknown
  'referencedBy': unknown
  'registryName': unknown
  'required': unknown
  'rerun': unknown
  'resetFilters': unknown
  'resilienceOverview': unknown
  'resilienceProbes': unknown
  'resilienceRate': unknown
  'resilienceScoreOverview': unknown
  'resilienceScoreTooltip': unknown
  'resilienceScoreTrends': unknown
  'resilienceStepCanHelpYou': unknown
  'resilienceTabDescription': unknown
  'resiliencyScore': unknown
  'resource': unknown
  'responseCode': unknown
  'responseTimeout': unknown
  'responseType': unknown
  'resultAfterExecution': unknown
  'resultMetExpectations': unknown
  'resultSummary': unknown
  'resultsMetExpectations': unknown
  'resultsSummary': unknown
  'retry': unknown
  'retryOptional': unknown
  'revertSchedule': unknown
  'revertScheduleText': unknown
  'run': unknown
  'runAllExperiment': unknown
  'runAt': unknown
  'runCommand': unknown
  'runCommands': unknown
  'runCreatedOn': unknown
  'runCreatedSuccessfully': unknown
  'runDailyAt': unknown
  'runDetails': unknown
  'runEvery': unknown
  'runHistory': unknown
  'runLogsNotAvailableYet': unknown
  'runMarkedAsCompleted': unknown
  'runNow': unknown
  'runOn': unknown
  'runOnSpecificDay': unknown
  'runOnSpecificDayMonth': unknown
  'running': unknown
  'runs': unknown
  'save': unknown
  'saveAndContinue': unknown
  'saveToChaosHub': unknown
  'saveToChaosHubSuccess': unknown
  'saveValues': unknown
  'schedule': unknown
  'scheduleType': unknown
  'scheduledBy': unknown
  'scheduledFor': unknown
  'scope': unknown
  'search': unknown
  'searchExperimentRunID': unknown
  'searchExperiments': unknown
  'searchForAProbe': unknown
  'searchForChaosFaults': unknown
  'searchForHub': unknown
  'searchForMonitoredServices': unknown
  'searchHub': unknown
  'secret': unknown
  'seeAllChaosHubs': unknown
  'seeAllChaosInfrastructures': unknown
  'seeAllEnvironments': unknown
  'seeAllFaults': unknown
  'selectAppKind': unknown
  'selectAppLabel': unknown
  'selectAppNamespace': unknown
  'selectChaosExperiment': unknown
  'selectChaosInfrastructure': unknown
  'selectChaosInfrastructureFormLabel': unknown
  'selectChaosInfrastructureType': unknown
  'selectDeployChaosInfrastructure': unknown
  'selectExperimentToViewDetails': unknown
  'selectExperiments': unknown
  'selectHub': unknown
  'selectHubFromList': unknown
  'selectHubHeader': unknown
  'selectProbes': unknown
  'selectProject': unknown
  'selectTimeframe': unknown
  'selectYourProbe': unknown
  'selectYourProbeType': unknown
  'selectedExperiments': unknown
  'sequence': unknown
  'serviceAccount': unknown
  'serviceAccountName': unknown
  'serviceHealthScore': unknown
  'setFaultWeights': unknown
  'setupChaosInfrastructures': unknown
  'setupProbe': unknown
  'setupProbeBtn': unknown
  'showLess': unknown
  'showingAll': unknown
  'showingLastRuns': unknown
  'signOut': unknown
  'singleRun': unknown
  'source': unknown
  'specificNamespaceAccess': unknown
  'stages': unknown
  'startBlankCanvasDescription': unknown
  'startBlankCanvasTitle': unknown
  'startTime': unknown
  'startWith': unknown
  'startedAt': unknown
  'startedOn': unknown
  'startingWith': unknown
  'status': unknown
  'statusCheck': unknown
  'stop': unknown
  'stopAllDesc': unknown
  'stopAllExp': unknown
  'stopAllHeading': unknown
  'stopExpRun': unknown
  'stopExpRunDesc': unknown
  'stopExpRuns': unknown
  'stopExperimentDesc': unknown
  'stopExperimentHeading': unknown
  'stopOnFailure': unknown
  'stopped': unknown
  'stoppedRuns': unknown
  'stoppedSuccessfully': unknown
  'succeeded': unknown
  'success': unknown
  'successSummary': unknown
  'suggestion1': unknown
  'summary': unknown
  'switchToBarChart': unknown
  'switchToLineChart': unknown
  'syncLatestRun': unknown
  'syncedSuccessfully': unknown
  'tags': unknown
  'target': unknown
  'targetApplication': unknown
  'targetInfrastructure': unknown
  'taskIDSuccess': unknown
  'templateFromChaosHubsDescription': unknown
  'templateFromChaosHubsTitle': unknown
  'templateFromProjectDescription': unknown
  'templateFromProjectTitle': unknown
  'testConnection': unknown
  'testSuccess': unknown
  'testingConnection': unknown
  'thisExperimentHasNoRuns': unknown
  'timeout': unknown
  'toleration.effectPlaceholder': unknown
  'toleration.keyPlaceholder': unknown
  'toleration.operatorPlaceholder': unknown
  'toleration.title': unknown
  'toleration.valuePlaceholder': unknown
  'tolerationSeconds': unknown
  'tolerationText': unknown
  'topology': unknown
  'total': unknown
  'totalChaosHubs': unknown
  'totalChaosInfrastructures': unknown
  'totalEnvironments': unknown
  'totalExp': unknown
  'totalExperiments': unknown
  'totalRuns': unknown
  'triggeredBy': unknown
  'troubleshooting': unknown
  'tuneFault': unknown
  'tuneFaultProperties': unknown
  'tuneFaultWeight': unknown
  'tuneWeight': unknown
  'type': unknown
  'unableToGetProbes': unknown
  'unhealthy': unknown
  'update': unknown
  'updatedAt': unknown
  'updatedBy': unknown
  'upgradeChaosInfrastructure': unknown
  'upgradeManifestDownloadedSuccessfully': unknown
  'uploadYAMLButton': unknown
  'uploadYAMLDescription': unknown
  'uploadYAMLDescriptionBuilder': unknown
  'uploadYAMLDragText': unknown
  'uploadYAMLTitle': unknown
  'uploadYAMLTitleBuilder': unknown
  'uploadYaml': unknown
  'url': unknown
  'useIntegerValue': unknown
  'useThisTemplate': unknown
  'validationError': unknown
  'value': unknown
  'valuePlaceholder': unknown
  'version': unknown
  'view': unknown
  'viewAllDefaultProperties': unknown
  'viewAllExperiments': unknown
  'viewAllRuns': unknown
  'viewDetailedExecution': unknown
  'viewExecution': unknown
  'viewExecutions': unknown
  'viewExperimentManifest': unknown
  'viewInChaosModule': unknown
  'viewLastExecution': unknown
  'viewLessDefaultProperties': unknown
  'viewLogs': unknown
  'viewManifest': unknown
  'viewProbeDetails': unknown
  'viewProbeProperties': unknown
  'viewRun': unknown
  'warning': unknown
  'weekly': unknown
  'weeklyMessage': unknown
  'weightAdjustDescription': PrimitiveObject<'numberOfFaults' | 'experimentName'>
  'weightAdjustHeader': unknown
  'welcomeToLitmus': unknown
  'yearlyTabTitle': unknown
}