select count(w_id) from warehouse;
select count(d_w_id) from district;
select count(c_w_id) from customer;
select count(h_c_id) from history;
select count(no_w_id) from new_orders;
select count(o_w_id) from orders;
select count(ol_w_id) from order_line;
select count(i_id) from item;
select count(s_w_id) from stock;
