---
apiVersion: batch/v1
kind: Job
metadata:
  name: tpcc-bench
spec:
  template:
    metadata:
      name: tpcc-bench
      labels:
        loadgen_lkey: loadgen_lvalue
    spec:
      restartPolicy: Never
      containers:
      - name: tpcc-bench 
        image: openebs/tests-tpcc-client
        command: ["/bin/bash"]
        args: ["-c", "./tpcc-runner.sh service_ip tpcc.conf; exit 0"]
        volumeMounts:
        - name: tpcc-configmap
          mountPath: /tpcc-mysql/tpcc.conf
          subPath: tpcc.conf
        tty: true 
      volumes:
        - name: tpcc-configmap
          configMap:
            name: tpcc-config
