/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface ApiToken {
  created_at?: number;
  expires_at?: number;
  name?: string;
  token?: string;
  user_id?: string;
}
