/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface CreateApiTokenResponse {
  accessToken?: string;
  type?: string;
}
