/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface ErrorModel {
  /**
   * @format int32
   */
  code?: number;
  error?: string;
  errorDescription?: string;
}
