/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { ApiToken } from '../schemas/ApiToken';

export interface GetApiTokensResponse {
  apiTokens: ApiToken[];
}
