/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { ProjectMember } from '../schemas/ProjectMember';

export interface GetInvitationResponse {
  invitationRole: 'Executor' | 'Owner' | 'Viewer' | 'Editor';
  projectID: string;
  projectName: string;
  projectOwner: ProjectMember;
}
