/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface ProjectMember {
  email?: string;
  invitation: 'Accepted' | 'Declined' | 'Exited' | 'Pending';
  joinedAt?: string;
  name?: string;
  role: 'Executor' | 'Owner' | 'Viewer' | 'Editor';
  userID: string;
  username: string;
}
