/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

export interface ResponseErrOldPassword {
  /**
   * @example "The old and new passwords can't be same"
   */
  error?: string;
  /**
   * @example "The old and new passwords can't be same"
   */
  errorDescription?: string;
}
