/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.
import type { ActionBy } from '../schemas/ActionBy';

export interface User {
  createdAt?: number;
  createdBy?: ActionBy;
  email?: string;
  isRemoved: boolean;
  name?: string;
  role: string;
  updatedAt?: number;
  updatedBy?: ActionBy;
  userID: string;
  username: string;
}
