---
apiVersion: batch/v1
kind: Job
metadata:
  name: litmus-cassandra-loadgen
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: loadgen
        image: openebs/ansible-runner
        imagePullPolicy: Always
        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            #value: log_plays
            value: default

          - name: RUN_ID
            value: "" 
            
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./cassandra/workload/test.yml -i /etc/ansible/hosts -v; exit 0"]
        
