#!/bin/bash

## initialize retcode counter
rc_counter=0

## perform syntax-check against each playbook
for i in $(find ./ -iname *.yml -printf '%P\n' | grep 'ansible_logic.yml'); do 
	ansible-playbook $i --syntax-check -i /etc/ansible/hosts -v;
	rc=$?; rc_counter=$((rc_counter+rc));         	
done
exit ${rc_counter}
