---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: percona-liveness-
  namespace: litmus
spec:
  activeDeadlineSeconds: 5400
  template:
    metadata:
      name: percona-liveness
      namespace: litmus
      labels:
        # label used to track percona liveness job by ci-tool/test
        liveness: percona-liveness

        # label used for mass-liveness check upon infra-chaos
        infra-aid: liveness

    spec:
      serviceAccountName: litmus
      restartPolicy: Never

      #nodeSelector:
      #  kubernetes.io/hostname: 

      tolerations:
        - key: "infra-aid"
          value: "observer"
          operator: "Equal"
          effect: "NoSchedule"
 
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always
        env: 
          - name: ANSIBLE_STDOUT_CALLBACK
            value: default

          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./apps/percona/liveness/test.yml -i /etc/ansible/hosts -v; exit 0"]

      - name: percona-liveness  
        image: openebs/tests-mysql-client
        env:
          # Time period (in sec) b/w retries for DB init check
          - name: INIT_WAIT_DELAY
            value: "30"
 
          # No of retries for DB init check
          - name: INIT_RETRY_COUNT
            value: "10"

          # Time period (in sec) b/w liveness checks
          - name: LIVENESS_PERIOD_SECONDS
            value: "10"

          # Time period (in sec) b/w retries for db_connect failure            
          - name: LIVENESS_TIMEOUT_SECONDS
            value: "10"

          # No of retries after a db_connect failure before declaring liveness fail
          - name: LIVENESS_RETRY_COUNT
            value: "6"

          # Application service label
          - name: DB_SVC 
            value: percona-mysql.app-percona-ns.svc.cluster.local 

          # Database username  
          - name: DB_USER
            value: root
 
          # Database password
          - name: DB_PASSWORD
            value: k8sDem0

        command: ["/bin/bash"]
        args: ["-c", "bash mysql-liveness-check.sh; exit 0"]
        tty: true 
