---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: datastax-app-chaos-
  namespace: litmus
spec:
  template:
    metadata:
      labels:
        name: datastax-app-chaos
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        env:
          - name: ANSIBLE_STDOUT_CALLBACK
            value: default

          - name: APP_NAMESPACE
            value: datastax-cstor 

          - name: APP_LABEL
            value: 'app=dse'

          - name: DEPLOY_TYPE
            value: statefulset

        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./apps/datastax/chaos/dse_pod_failure/test.yml -i /etc/ansible/hosts -vv; exit 0"]
