---
apiVersion: batch/v1
kind: Job
metadata:
  name: litmus-openebs-cleanup
  namespace: litmus 
spec:
  template:
    metadata:
      name: litmus
      labels:
        provider: openebs-cleanup
    spec:
      serviceAccountName: litmus
      restartPolicy: Never
      containers:
      - name: ansibletest
        image: openebs/ansible-runner:ci
        imagePullPolicy: Always
        env: 
          - name: mountPath
            value: /mnt/openebs
          - name: ANSIBLE_STDOUT_CALLBACK
            value: actionable
          - name: RUN_ID
            value:
        command: ["/bin/bash"]
        args: ["-c", "ansible-playbook ./operator/master/ansible/openebs_cleanup.yaml -i /etc/ansible/hosts -vv; exit 0"]
        volumeMounts:
          - name: kubeconfig 
            mountPath: /root/admin.conf
            subPath: admin.conf
          - name: logs
            mountPath: /var/log/ansible 
      volumes: 
        - name: kubeconfig
          configMap: 
            name: kubeconfig 
        - name: logs 
          hostPath:
            path: /mnt/openebs
            type: ""
