---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:
        - block:

            - name: Record test instance/run ID
              set_fact:
                run_id: "{{ lookup('env','RUN_ID') }}"

            - name: Construct testname appended with runID
              set_fact:
                test_name: "{{ test_name }}-{{ run_id }}"

          when: lookup('env','RUN_ID')

        ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /utils/fcm/update_litmus_result_resource.yml
          vars:
            status: 'SOT'

        - name: Checking the status  of test specific namespace.
          shell: kubectl get ns {{ namespace }} -o jsonpath='{.status.phase}'
          args:
           executable: /bin/bash
          register: npstatus
          until: "'Active' in npstatus.stdout"
          delay: 30
          retries: 10
        
        # Checking if the application is deployed.
        
        - name: Obtaining the number of statefulset replicas.
          shell: kubectl get statefulset -n {{ namespace }} -l {{ app_label }} -o custom-columns=:spec.replicas
          args:
            executable: /bin/bash
          register: rep_count
          until: "rep_count.rc == 0"
          delay: 60
          retries: 15

        - name: Obtain the ready replica count and compare with the replica count.
          shell: kubectl get statefulset -n {{ namespace }} -l {{ app_label }} -o custom-columns=:..readyReplicas
          args:
            executable: /bin/bash
          register: ready_rep
          until: "ready_rep.rc == 0 and ready_rep.stdout|int == rep_count.stdout|int"
          delay: 60
          retries: 30
        
        - name: Obtaining the loadgen pod label from env.
          set_fact:
            loadgen_lkey: "{{ loadgen_label.split('=')[0] }}"
            loadgen_lvalue: "{{ loadgen_label.split('=')[1] }}"

        - name: Replace the label in loadgen job spec.
          replace:
            path: "{{ mongodb_loadgen }}"
            regexp: "loadgen_lkey: loadgen_lvalue"
            replace: "{{ loadgen_lkey }}: {{ loadgen_lvalue }}"

        - name: Replace service placeholder in mongo-loadgen
          replace:
            path: "{{ mongodb_loadgen }}"
            regexp: "servicename"
            replace: "{{ lookup('env','SERVICE_NAME') }}"

        - name: Replace pod placeholder in mongo-loadgen
          replace:
            path: "{{ mongodb_loadgen }}"
            regexp: "podname"
            replace: "{{ lookup('env','POD_NAME') }}" 

        - name: Replace database-name placeholder in mongo-loadgen
          replace:
            path: "{{ mongodb_loadgen }}"
            regexp: "database_name"
            replace: "{{ lookup('env','DATABASE_NAME') }}"       
        
        - name: Create Mongodb Loadgen Job
          shell: kubectl apply -f {{ mongodb_loadgen }} -n {{ namespace }} 

        - name: Verify load-gen pod is running
          shell: kubectl get pods -n {{ namespace }} -l {{ loadgen_label }} -o jsonpath='{.items[0].status.phase}'
          args:
            executable: /bin/bash
          register: result
          until: "'Running' in result.stdout"
          delay: 30
          retries: 15

        - name: Verifying load-generation  
          shell: kubectl exec -it mongo-0 -n {{ namespace }} -- mongo --eval 'db.getMongo().getDBNames()'
          register: output
          until: "'sbtest' in output.stdout"
          delay: 30
          retries: 15

        - set_fact:
            flag: "Pass"

      rescue:
        - set_fact:
            flag: "Fail"  

      always:
            ## RECORD END-OF-TEST IN LITMUS RESULT CR 
        - include_tasks: /utils/fcm/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
