#!/bin/bash
set -e

IMAGEID=$( docker images -q openebs/tests-mysql-master )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ]; 
then 
  docker login -u "${DNAME}" -p "${DPASS}"; 
  #Push to docker hub repository with latest tag
  docker tag ${IMAGEID} openebs/tests-mysql-master:latest
  docker push openebs/tests-mysql-master:latest; 
else
  echo "No docker credentials provided. Skip uploading openebs/tests-mysql-master:latest to docker hub"; 
fi;
