/* eslint-disable */
// This code is autogenerated using @harnessio/oats-cli.
// Please do not modify this code directly.

/**
 * @example {"projectID":"384f6666-3b7d-4381-b5b5-bfc4c3dedbc8","userID":"3bdc0bd9-fc46-433b-ac21-05d555566c46"}
 */

export interface DeclineInvitationBodyRequestBody {
  projectID: string;
  userID: string;
}
