# delete-gpd.yml
# Description:  This Ansible playbook will remove the previously attached GPDs to the Cluster
# Author: Harshvardhan Karn
###############################################################################################
#Test Steps:
#
# 1. Get Cluster name, if not provided
# 2. Get the nodes name from the specified cluster
# 3. Use the fetched node to get the GPDs, then detach and delete
#
###############################################################################################
---
- hosts: localhost
  vars:
    files: 
    email: 
    project: 
    cluster_name:
  tasks:
    - name: Fetching Cluster Name
      shell: cat ~/logs/clusters
      register: cluster_name
      when: not cluster_name

    - set_fact:
        cluster_name: "{{ cluster_name.stdout }}"
      when: cluster_name.stdout is defined

    - name: Get nodes
      command:  gcloud compute instances list --filter="metadata.items.key['cluster-name']['value']~'{{cluster_name}}' name~'nodes'" --format json
      register: response
      
    - set_fact:
        data: "{{ response.stdout }}"

    - local_action:
        module: gce_pd
        state: deleted
        credentials_file: "{{ files }}"
        service_account_email: "{{ email }}"
        project_id: "{{ project }}"
        instance_name: "{{item.name }}"
        zone: us-central1-a
        name: "{{ item.name + '-' + 'gpd' }}"
      with_items: "{{ data }}"

