---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:

        ## Generating the testname for deployment
        - include_tasks: /utils/fcm/create_testname.yml

        ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /utils/fcm/update_litmus_result_resource.yml
          vars:
            status: 'SOT'

        - name: Replace the storage capacity placeholder
          replace:
             path: "{{ application_deployment }}"
             regexp: "volume-capacity"
             replace: "{{ lookup('env','CAPACITY') }}" 

        - name: Replace the affinity label annotation in statefulset yml
          replace:
             path: "{{ application_deployment }}"
             regexp: "affinity_label"
             replace: "{{ affinity_label }}"              
       
        - block:
         ## Actual test
         ## Creating namespaces and making the application for deployment
            - include_tasks: /utils/k8s/pre_create_app_deploy.yml

            - name: Replace the default namespace in cassandra statefulset yaml
              replace:
                path: "{{ application_deployment }}"
                regexp: 'cassandra-0.cassandra.default.svc.cluster.local'
                replace: 'cassandra-0.cassandra.{{ app_ns }}.svc.cluster.local'

             ## Deploying the application
            - include_tasks: /utils/k8s/deploy_single_app.yml
              vars:
                check_app_pod: 'no'
                delay: 10
                retries: 20

          when: "'deprovision' not in action"

        - block:

            - name: Deprovisioning the Application
              include_tasks: /utils/k8s/deprovision_statefulset.yml
              vars:
                app_deployer: "{{ application_deployment }}"

          when: "'deprovision' is in action"

        - set_fact:
            flag: "Pass"

      rescue:
        - name: Setting fail flag
          set_fact:
            flag: "Fail"

      always:
        ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /utils/fcm/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
